# Social Network Analysis - Class 10 - Structural Equivalence

In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
import networkx as nx
import igraph as ig

In [2]:
trade = pd.read_csv('Data/trade.csv')

In [33]:
trade

,ALGERIA,ARGENTINA,BRAZIL,CHINA,CZECHOSLOVAKIA,ECUADOR,EGYPT,ETHIOPIA,FINLAND,HONDURAS,...,MADAGASCAR,NEW_ZEALAND,PAKISTAN,SPAIN,SWITZERLAND,SYRIA,THAILAND,UNITED_KINGDOM,UNITED_STATES,YUGOSLAVIA
0,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,1,0,1,1,0,1,0,0,1,0,...,0,0,1,1,1,0,1,0,1,0
2,1,1,0,1,1,1,1,0,1,1,...,0,1,1,1,1,1,1,1,1,1
3,1,1,1,0,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,1,1,1,1,0,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
5,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,0,0,0,0,1,0,0,1,1,0,...,0,0,0,1,1,0,0,1,1,1
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
8,1,1,1,1,1,1,1,1,0,1,...,0,1,1,1,1,1,1,1,1,1
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10,1,0,0,1,1,0,1,0,1,0,...,0,1,1,1,1,0,1,1,1,1
11,0,1,0,0,0,0,0,1,1,0,...,0,1,0,1,1,0,1,1,1,1
12,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
15,1,0,0,1,0,0,1,0,0,0,...,0,0,1,1,0,0,1,1,1,1
16,0,0,0,1,1,0,0,0,1,0,...,0,1,0,1,1,1,1,1,1,0
17,1,1,1,1,1,1,1,0,1,1,...,1,1,1,0,1,1,1,1,1,1
18,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,0,1,1,1,1,1
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,1,1,0,0,0,0,1,0,...,0,1,1,1,1,1,0,1,1,1
21,1,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,0,1,1
22,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,1
23,1,1,0,1,1,0,1,1,1,0,...,0,1,1,1,1,1,1,1,1,0

In [4]:
trade.corr()

,ALGERIA,ARGENTINA,BRAZIL,CHINA,CZECHOSLOVAKIA,ECUADOR,EGYPT,ETHIOPIA,FINLAND,HONDURAS,...,MADAGASCAR,NEW_ZEALAND,PAKISTAN,SPAIN,SWITZERLAND,SYRIA,THAILAND,UNITED_KINGDOM,UNITED_STATES,YUGOSLAVIA
ALGERIA,1.000000,0.607808,0.510490,0.669342,0.496503,0.712525,0.919866,0.438187,0.496609,0.712525,...,0.531085,0.579538,0.918780,0.513610,0.496609,0.585369,0.842075,0.329630,0.434524,0.496609
ARGENTINA,0.607808,1.000000,0.409917,0.305505,0.438187,0.567367,0.676123,0.657143,0.480079,0.741941,...,0.487950,0.714286,0.542857,0.356386,0.480079,0.676123,0.654654,0.542326,0.292770,0.480079
BRAZIL,0.510490,0.409917,1.000000,0.367058,0.174825,0.669342,0.418121,0.409917,0.367058,0.669342,...,0.627646,0.438187,0.607808,0.222309,0.367058,0.585369,0.367058,0.038329,0.337963,0.367058
CHINA,0.669342,0.305505,0.367058,1.000000,0.496609,0.600000,0.602464,0.130931,0.466667,0.422222,...,0.248452,0.567367,0.741941,0.449712,0.466667,0.602464,0.644444,0.260360,0.347833,0.466667
CZECHOSLOVAKIA,0.496503,0.438187,0.174825,0.496609,1.000000,0.367058,0.585369,0.438187,0.496609,0.539792,...,0.531085,0.579538,0.409917,0.329630,0.496609,0.585369,0.496609,0.329630,0.241402,0.496609
ECUADOR,0.712525,0.567367,0.669342,0.600000,0.367058,1.000000,0.602464,0.392792,0.422222,0.822222,...,0.546594,0.480079,0.654654,0.307698,0.422222,0.602464,0.600000,0.118345,0.248452,0.422222
EGYPT,0.919866,0.676123,0.418121,0.602464,0.585369,0.602464,1.000000,0.507093,0.430331,0.774597,...,0.577350,0.676123,0.845154,0.458349,0.430331,0.666667,0.774597,0.458349,0.384900,0.602464
ETHIOPIA,0.438187,0.657143,0.409917,0.130931,0.438187,0.392792,0.507093,1.000000,0.480079,0.567367,...,0.487950,0.542857,0.371429,0.542326,0.480079,0.507093,0.480079,0.356386,0.292770,0.480079
FINLAND,0.496609,0.480079,0.367058,0.466667,0.496609,0.422222,0.430331,0.480079,1.000000,0.422222,...,0.447214,0.741941,0.567367,0.639064,0.822222,0.602464,0.644444,0.449712,0.546594,0.466667
HONDURAS,0.712525,0.741941,0.669342,0.422222,0.539792,0.822222,0.774597,0.567367,0.422222,1.000000,...,0.745356,0.654654,0.654654,0.307698,0.422222,0.774597,0.600000,0.307698,0.248452,0.600000
INDONESIA,0.749159,0.542857,0.607808,0.741941,0.409917,0.654654,0.676123,0.371429,0.567367,0.654654,...,0.487950,0.657143,0.828571,0.573316,0.567367,0.845154,0.741941,0.387376,0.487950,0.392792
ISRAEL,0.607808,0.485714,0.579538,0.654654,0.438187,0.741941,0.507093,0.314286,0.480079,0.567367,...,0.487950,0.542857,0.714286,0.356386,0.480079,0.676123,0.480079,0.170445,0.292770,0.305505
JAPAN,0.513610,0.356386,0.222309,0.639064,0.513610,0.307698,0.458349,0.356386,0.639064,0.307698,...,0.158777,0.573316,0.573316,0.596639,0.639064,0.458349,0.639064,0.394958,0.476331,0.639064
LIBERIA,0.539792,0.567367,0.496609,0.422222,0.539792,0.644444,0.602464,0.392792,0.600000,0.822222,...,0.745356,0.654654,0.480079,0.307698,0.422222,0.774597,0.600000,0.307698,0.248452,0.422222
MADAGASCAR,0.531085,0.487950,0.627646,0.248452,0.531085,0.546594,0.577350,0.487950,0.447214,0.745356,...,1.000000,0.487950,0.487950,0.158777,0.248452,0.577350,0.447214,0.158777,0.111111,0.447214
NEW_ZEALAND,0.579538,0.714286,0.438187,0.567367,0.579538,0.480079,0.676123,0.542857,0.741941,0.654654,...,0.487950,1.000000,0.657143,0.573316,0.741941,0.845154,0.741941,0.573316,0.487950,0.567367
PAKISTAN,0.918780,0.542857,0.607808,0.741941,0.409917,0.654654,0.845154,0.371429,0.567367,0.654654,...,0.487950,0.657143,1.000000,0.573316,0.567367,0.676123,0.741941,0.387376,0.487950,0.567367
SPAIN,0.513610,0.356386,0.222309,0.449712,0.329630,0.307698,0.458349,0.542326,0.639064,0.307698,...,0.158777,0.573316,0.573316,1.000000,0.639064,0.458349,0.639064,0.596639,0.476331,0.449712
SWITZERLAND,0.496609,0.480079,0.367058,0.466667,0.496609,0.422222,0.430331,0.480079,0.822222,0.422222,...,0.248452,0.741941,0.567367,0.639064,1.000000,0.602464,0.644444,0.449712,0.546594,0.466667
SYRIA,0.585369,0.676123,0.585369,0.602464,0.585369,0.602464,0.666667,0.507093,0.602464,0.774597,...,0.577350,0.845154,0.676123,0.458349,0.602464,1.000000,0.602464,0.458349,0.384900,0.430331
THAILAND,0.842075,0.654654,0.367058,0.644444,0.496609,0.600000,0.774597,0.480079,0.644444,0.600000,...,0.447214,0.741941,0.741941,0.639064,0.644444,0.602464,1.000000,0.449712,0.546594,0.466667
UNITED_KINGDOM,0.329630,0.542326,0.038329,0.260360,0.329630,0.118345,0.458349,0.356386,0.449712,0.307698,...,0.158777,0.573316,0.387376,0.596639,0.449712,0.458349,0.449712,1.000000,0.264628,0.449712
UNITED_STATES,0.434524,0.292770,0.337963,0.347833,0.241402,0.248452,0.384900,0.292770,0.546594,0.248452,...,0.111111,0.487950,0.487950,0.476331,0.546594,0.384900,0.546594,0.264628,1.000000,0.347833
YUGOSLAVIA,0.496609,0.480079,0.367058,0.466667,0.496609,0.422222,0.602464,0.480079,0.466667,0.600000,...,0.447214,0.567367,0.567367,0.449712,0.466667,0.430331,0.466667,0.449712,0.347833,1.000000

One way to do blockmodels in Python. This is an example from the `networkx` documentation. For more details, see https://networkx.github.io/documentation/stable/auto_examples/algorithms/plot_blockmodel.html

In [3]:
countrynames = trade.index

# Need to make index numbers as well for the adjacency matrix
trade.index = list(np.arange(1, 25))
trade.columns = list(np.arange(1, 25))

In [4]:
# create directed graph
g = nx.from_pandas_adjacency(trade, create_using=nx.DiGraph())

nx.write_edgelist(g, "test.edgelist")

In [64]:
# code based on https://networkx.github.io/documentation/stable/auto_examples/algorithms/plot_blockmodel.html

from scipy.spatial import distance
from scipy.cluster import hierarchy
from collections import defaultdict

def create_hc(G, t=1):
    """Creates hierarchical cluster of graph G from distance matrix"""
    path_length = nx.all_pairs_shortest_path_length(G)
    distances = np.zeros((len(G), len(G)))
    for u, p in path_length:
        for v, d in p.items():
            distances[u][v] = d
            
    # Create hierarchical cluster
    Y = distance.squareform(distances)
    Z = hierarchy.complete(Y)  # Creates HC using farthest point linkage
    
    # This partition selection is arbitrary, for illustrive purposes
    # higher t leads to lower number of clusters
    membership = list(hierarchy.fcluster(Z, t=t, criterion='distance'))
    
    # Create collection of lists for blockmodel
    partition = defaultdict(list)
    for n, p in zip(list(range(len(G))), membership):
        partition[p].append(n)
        
    return list(partition.values())

G=nx.read_edgelist("test.edgelist")

# Extract largest connected component into graph H
H = next(nx.connected_component_subgraphs(G))

# Makes life easier to have consecutively labeled integer nodes
H = nx.convert_node_labels_to_integers(H)

# Create parititions with hierarchical clustering
partitions = create_hc(H, t=1)

# Build blockmodel graph
BM = nx.quotient_graph(H, partitions, relabel=True)

Based on testing of this particular dataset, setting t<1 generates as many clusters as there are vertices. t>=1 and t<2 generates 9 clusters. And t >= 2 generates 1 cluster.

In [65]:
# clusters formed for the vertices

partitions

[[0, 1, 2, 3, 4, 6, 10, 21],
 [5, 7, 12],
 [8, 13, 22],
 [9, 17],
 [11, 14, 15, 23],
 [16],
 [18],
 [19],
 [20]]